- search.go
Don't sure need or not some tests for it
> search explanation response types

- get.go
- get_test.go
This seems to have got lost in the shuffle to v2.
Thanks again!
> Restore FetchSourceContext feature

- suggest_field.go
As shown in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/suggester-context.html) it's possible to set a context for suggest fields. 
It should be possible to set this context when indexing a new document
> Add method to set context queries for a suggest field

- bulk_delete_request.go
- bulk_delete_request_test.go
> Revert "Feature/bulk delete request parent"

- nodes_info.go
Changed JVM from NodesInfoNodeProcess type to NodesInfoNodeJVM type (issue #475)
> Fixed issue with NodesInfoResponse (#475)

- client.go
- indices_get_field_mapping.go
- indices_get_field_mapping_test.go
Add support for Get Field Mapping API: https://www.elastic.co/guide/en/elasticsearch/reference/5.2/indices-get-field-mapping.html
This is largely based on Get Mapping API code.
> Add Get Field Mapping API 

- backoff.go
- backoff_test.go
- client.go
- retrier.go
- retrier_test.go
> Retrier backport for elastic.v2

- backoff_test.go
- client.go
As reported by `staticcheck` from https://github.com/dominikh/go-tools
> fix staticcheck warnings

- README.md
- client.go
- search_shards.go
- search_shards_test.go
Added SearchShards API functionality + minimum tests.
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/search-shards.html
> SearchShards API added + tests

- README.md
- client.go
- validate.go
- validate_test.go
Added Validate API and some minimal tests
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/search-validate.html
> Validate api

- README.md
- search_aggs.go
- search_aggs_bucket_adjacency_matrix.go
- search_aggs_bucket_adjacency_matrix_test.go
- search_aggs_test.go
Adjacency matrix aggregation added + tests
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-aggregations-bucket-adjacency-matrix-aggregation.html
> Adjacency matrix

- README.md
- search_aggs.go
- search_aggs_bucket_diversified_sampler.go
- search_aggs_bucket_diversified_sampler_test.go
- search_aggs_test.go
Added Diversified Sampler Aggs + tests
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-diversified-sampler-aggregation.html
> Added Diversified Sampler Aggs + tests

- README.md
- search_aggs.go
- search_aggs_metrics_geo_centroid.go
- search_aggs_metrics_geo_centroid_test.go
- search_aggs_test.go
Added Geo Centroid aggregation + minimal tests
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-geocentroid-aggregation.html
> Added Geo Centroid aggregation + minimal tests

- search_aggs_pipeline_avg_bucket.go
- search_aggs_pipeline_bucket_script.go
- search_aggs_pipeline_bucket_selector.go
- search_aggs_pipeline_cumulative_sum.go
- search_aggs_pipeline_derivative.go
- search_aggs_pipeline_max_bucket.go
- search_aggs_pipeline_min_bucket.go
- search_aggs_pipeline_mov_avg.go
- search_aggs_pipeline_mov_avg_test.go
- search_aggs_pipeline_percentiles_bucket.go
- search_aggs_pipeline_serial_diff.go
- search_aggs_pipeline_stats_bucket.go
- search_aggs_pipeline_sum_bucket.go
All subAggregation properties and methods removed from Pipeline Aggregations
> #734 Issue https://github.com/olivere/elastic/issues/734

- nodes_info.go
This will add the Roles field to node info
> Added roles field to node info

- search_queries_simple_query_string.go
> add quote_field_suffix to simple_query_string

- bulk.go
- bulk_test.go
same as https://github.com/olivere/elastic/pull/777
> Change bulk reset func to exportable v5

- bulk.go
- bulk_test.go
same as https://github.com/olivere/elastic/pull/777
> Change bulk reset func to exportable v3

- bulk.go
- bulk_test.go
same as https://github.com/olivere/elastic/pull/777
> Change bulk reset func to exportable v2

- bulk_processor.go
When Elasticsearch gets overloaded it may return response code 429
for line items in the bulk response that it could not process.  This
commit detects that response code and requeues the line item so that it
is not dropped.
For reference see the code in the elastic beats elasticsearch
output plugin.
https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/client.go#L500.
> Requeue bulk items with response code 429 - Too Many Requests

- scroll.go
- scroll_test.go
I'm afraid I forgot to include this in PR #929, sorry for the noise.
> Add ScrollService.MaxResponseSize()

- client.go
- setup_test.go
- xpack_info.go
- xpack_info_test.go
- xpack_security_delete_role.go
- xpack_security_delete_role_mapping.go
- xpack_security_delete_role_mapping_test.go
- xpack_security_delete_role_test.go
- xpack_security_get_role.go
- xpack_security_get_role_mapping.go
- xpack_security_get_role_mapping_test.go
- xpack_security_get_role_test.go
- xpack_security_put_role.go
- xpack_security_put_role_mapping.go
- xpack_security_put_role_mapping_test.go
- xpack_security_put_role_test.go
- xpack_test.go
- xpack_watcher_get_watch_test.go
Added support for XPack Info API
Added support for XPack Security Role and Role Mapping API.
> xpack-security-role-and-role-mapping-api

- update_by_query.go
- update_by_query_test.go
Backport DoAsync to update_by_query.go
> added DoAsync method to elastic.v5

- README.md
I fixed two links in the readme file.
> Fix Doc: Add full url to md file

- .gitignore
- CONTRIBUTING.md
- scroll.go
This PR includes 2 minor fixes:
- Fix inconsistent comments about scroll alive time
- Fix stale link in contributing doc
- Also add IDE folder to gitignore
>  Fix inconsistent comments and stale links

- search_aggs.go
- search_aggs_test.go
add api for process scripted metric aggregation response
> Add ScriptedMetric Response Processing API
