olivere/elastic

reindexer.go, reindexer_test.go
That method allowed the caller to specify the index settings for
number_of_shards and number_of_replicas, but otherwise prevented the
user from specifying a mapping.
Removed the method and the two settings.
Now the caller must setup the target index any way he likes before
invoking the reindexer (this is in conformity with the reindexer
package comment)
=> Remove Reindexer.recreateTargetIndex

get.go, get_test.go, index_test.go
Using Fields in GetService resulted in a marshalling error.
Fixed the type of Fields to map[string]interface{}.
In get_test:
- Added a test that request two fields and asserts their value.
- Simplified two tests that were testing more than the GetService,
and were issuing unnecessary Flush calls.
=> Fix GetResult Fields type

client.go, index_test.go, reindexer.go, reindexer_test.go, scan.go, search_test.go
The reindexer now takes a HitHandler than can emit any kind of BulkRequest
We provide a CopyToTargetIndex function to handle the common case of straighforward copying from one index to another.
=> Generic handler

multi_get.go
Regarding documentation mget must not use underscore for "fields": 
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html#mget-fields
You can check it by this way:
curl -XGET es1:9200/_mget -d '{"docs" : [{"_id":1,"_index": "test_index","_fields":["name"]}]}’
curl -XGET es1:9200/_mget -d '{"docs" : [{"_id":1,"_index": "test_index","fields":["name"]}]}'
=> Multi Get must not use underscore for 'fields'

client.go
My long running application is showing a memory leak that profiles to the elastic search client.  Calling time. NewTicker() without calling Stop() on the ticker will create a memory leak.  Replace with After() to resolve.
=> Fix memory leak NewTicker -> After

percolate.go, percolate_test.go
Percolation on an existing document did not work because id was not being included in the url.
=> fix percolation on an existing document

bulk.go, bulk_delete_request.go, bulk_delete_request_test.go, bulk_index_request.go, bulk_index_request_test.go, bulk_update_request.go, bulk_update_request_test.go
When `BulkableRequest.Source()` is called, the underlying objects
now cache the result, preventing future calls from going through the
JSON marshaling process yet again.
`estimatedSizeInBytes` now acts directly on the values returned
by Source instead of calling String to avoid creating a bit of garbage. 
In addition, this does undo the change I mentioned in #252 as well, so that `estimatedSizeInBytes` is only called once per `BulkableRequest`. 
In my testing, these changes combined give a 20-30% increase in documents indexed per second compared to code at commit 629ba26e184081ae0b8d577ea45a253a88dd8615 (before the change to `estimatedSizeInBytes`). 
Fixes #252.
=> Cache calls to Source. Prevent unnecessary string creation

search.go
Add the query parameters relevant to [Multiple Indices](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/multi-index.html#multi-index) to v2.
I basically just copy/pasted what you have already implemented in v3.
=> Multi Indices query params to v2

client.go, field_stats.go, field_stats_test.go
Hi, 
I've been working on Field Stats support in the client. Note that it doesn't currently handle indices options such as expand wildcards, ignore unavailable etc. but I hope to add these soon.
=> Add Field Stats API

scroll.go, scroll_test.go
This is helpful if you issue many scroll queries and the automatic
timeout does not suffice.
=> Support clearing scroll queries

doc.go
Just a minor change, I missed that context had been added to newer versions and can see that examples etc have already been updated.
=> Update doc.go with context parameter for Do()

README.md
For reasons I can't find in code/docs, v5 requires a string for `func (s *ExistsService) Refresh` compared to the bool in v4. This simple updates the example in the v5 branch to match the code requirements.
I am also curious why it has changed while the RealTime parameter has not.
=> Updates example to provide string to refresh parameter.

search_aggs_bucket_terms.go, search_aggs_bucket_terms_test.go
resolve #486
https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-bucket-terms-aggregation.html
> Multiple criteria can be used to order the buckets by providing an array of order criteria such as the following:
=> Support Multiple Fields for Aggregation Order

client.go, snapshot_create_repository.go, snapshot_create_repository_test.go, snapshot_delete_repository.go, snapshot_delete_repository_test.go, snapshot_get_repository.go, snapshot_get_repository_test.go, snapshot_verify_repository.go, snapshot_verify_repository_test.go
This PR adds support for Elasticsearch's [snapshot repository API](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html).
Example program:
```go
package main
import (
"context"
"fmt"
elastic "gopkg.in/olivere/elastic.v5"
)
type FSSettings struct {
Location string `json:"location"`
}
func main() {
client, err := elastic.NewClient()
if err != nil {
panic(err)
}
repo := new(elastic.SnapshotRepository)
repo.Type = "fs"
settings := new(FSSettings)
settings.Location = "/tmp/elasticsearch"
repo.Settings = settings
_, err = client.SnapshotCreateRepository("repo1").BodyJson(repo).Do(context.TODO())
if err != nil {
panic(err)
}
repos, err := client.SnapshotGetRepository("repo1").Do(context.TODO())
if err != nil {
panic(err)
}
fmt.Printf("%v\n", repos)
verify, err …
```
=> Add Snapshot Repository API

indices_get_template.go
As per the Elasticsearch [docs][0], you can provide a "version" field that is used for external management of templates.  This adds the field to the response message so it can be read.
[0]: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html#versioning-templates
=> Add "version" field to IndicesGetTemplateResponse

bulk.go
In order to know if the bulk request returned 'noop' as the result, this commit added one more parameter to the BulkResponseItem struct.
=> Add more data on BulkResponseItem

client.go, client_test.go
Related to issue #510.
@olivere Let me know if you're OK with the level of detail added to `elastic.ErrNoClient`. Thanks.
=> Add extra info on client related errors

README.md, search_aggs.go, search_aggs_pipeline_percentiles_bucket.go, search_aggs_pipeline_percentiles_bucket_test.go, search_aggs_test.go
This PR adds the operations for a Percentiles Bucket aggregation, which is documented at https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-aggregations-pipeline-percentiles-bucket-aggregation.html.
=> Feature: Adds support for percentiles bucket pipeline aggregations

client.go, snapshot_create.go, snapshot_create_test.go
This PR adds support for Elasticsearch's [snapshot create API](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html).
Example program:
```go
package main
import (
"context"
"log"
"os"
"time"
elastic "gopkg.in/olivere/elastic.v5"
)
func main() {
client, err := elastic.NewClient()
if err != nil {
panic(err)
}
// create snapshot repo
repo := elastic.
NewSnapshotCreateRepositoryService(client).
Repository("repo1").
BodyJson(map[string]interface{}{
"type": "fs",
"settings": map[string]interface{}{
"location": "/tmp/elasticsearch",
},
})
repoResponse, err := repo.Do(context.TODO())
if err != nil {
panic(err)
}
if !repoResponse.Acknowledged {
panic("could not ack repository create")
}
// create snapshot
service := elastic.
NewSnapshotCreateService(client). …
```
=> Add Snapshot Create API

client.go, client_test.go
Hi! This PR fixes goroutine leaks caused by healthcheck not using ctx properly.
I've managed to reproduce it via tests.
=> [v*] Healthcheck goroutine leaks

suggester_completion.go, suggester_completion_test.go, suggester_context_category.go, suggester_context_category_test.go
Elasticsearch supports boosting by certain suggester categories - see [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/suggester-context.html#_category_query). 
This PR adds support for the boost field, while maintaining backwards compatibility.
**N.B.** The order of contexts is not important to the query, and so I didn't maintain their order in the json output. I didn't want to change the way you did tests (by parsing the json and comparing them), or add any new dependencies, so I simply gave the output two acceptable options. Hope that's ok.
=> Boost Suggestions by Context

suggester_term.go, suggester_term_test.go
Hi, 
I'm trying to query ES5.4 term suggester with prefix_lengh option, but I get error from server:
```   
"error": {
"type": "parsing_exception",
"reason": "suggester[term] doesn't support field [prefix_len]"
},
"status": 400
}
```
as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/search-suggesters-term.html#_other_term_suggest_options) "prefix_len" option name  is deprecated, it should be "prefix_length" for 5.x
=> Change prefix_len key to prefix_length in suggester options

errors.go
=> feat(errors): add IsConflict checker

client.go, reindex.go, reindex_test.go, tasks_get_task.go, tasks_list.go
When the `WaitForCompletion` parameter is set to `true`, the response from ElasticSearch is in a different format, as it just contains a task id. This PR provides a `Start` method on the ReindexService that will return the task id instead of the `BulkIndexByScrollResponse`, which is not appropriate for asynchronous requests. (I believe this could also be appropriate for the other Elastic APIs that have a `WaitForCompletion` parameter, although my present use case does not extend to them).
Secondly, the `TasksListService` does not work as expected with single `taskId` and `nodeId` values, so, for the simple case of monitoring a single task, I have added a `TasksGetTaskService`.
=> Support reindex as asynchronous task

update.go
According to Elasticsearch source code [1], the Result field should
be represented as a string and its possible values are represented
in Result enum [2].
[1] - https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/update/UpdateResponse.java
[2] - https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/DocWriteResponse.java#L66
=> Fix type of Result field for UpdateResponse. Issue #599

search_queries_fsq.go
Previously, FunctionScoreQuery only allowed either Query or Filter to be set,
setting the other to nil. There's no reason to do this, though, as
ElasticSearch allows both to be set.
See the equivalent Java code here:
https://github.com/elastic/elasticsearch/blob/v1.7.6/src/main/java/org/elasticsearch/index/query/functionscore/FunctionScoreQueryBuilder.java#L85-L88
=> v2: Let FunctionScoreQuery allow both Query and Filter

client.go
It appears that the logic for sniffing nodes between version 3 and 5 has diverged. I'm not entirely certain if this intentional or not. 
Currently, enabling sniffing in v3 and setting the client's scheme to `https` while querying against a cluster setup with [Search Guard SSL](https://github.com/floragunncom/search-guard-ssl) will produce an empty node list due to the fact that Search Guard will not return a `https_address` key for each node.
Here's a snippet of what a node returns for `GET /_nodes/http` with Search Guard SSL setup:
```
{
"cluster_name" : "elasticsearch-cluster",
"nodes" : {
"m1Mp_vxXRsudaMXvNeKtQg" : {
"transport_address" : "10.0.0.111:9300",
"host" : "10.0.0.111",
"ip" : "10.0.0.111",
"http_address" : "10.0.0.111:9200",
"http" : {
"bound_address" : [ "0.0.0.0:9200" ], …
```
=> Use v5 sniffNode logic in v3

search_suggester_test.go, setup_test.go, suggester_context.go, suggester_context_test.go
Elasticsearch has 4 types of suggesters, however only 3 are currently supported by elastic. This PR adds support for the fourth type of suggester, [context suggesters](https://www.elastic.co/guide/en/elasticsearch/reference/current/suggester-context.html). This fixes #561.
=> Add support for context suggesters

search.go, search_test.go, setup_test.go
_source can be nil in hits in my elastic it seems. This PR proposes to be more resilient to such entries and just skip them.
=> fix problems in search.go:Each when hits have 'nil' _Source field

count.go
Add support for terminate_after, as specified in 
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-count.html
=> add terminate_after to params

bulk_processor.go, bulk_processor_test.go
The behavior should be the same as before this commit, but this enables one to set a custom backoff policy.  A Stopbackoff e.g. would prevent retry.
=> customizable backoff for issue #646

search_aggs_bucket_date_range.go, search_aggs_bucket_date_range_test.go
See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html#time-zones
=> Add TimeZone to DateRangeAggregation

README.md, search_aggs_pipeline_bucket_sort.go, search_aggs_pipeline_bucket_sort_test.go
#730 
This PR adds the Bucket Sort pipeline aggregation to elastic client.
Few important things to notice:
1) As pipeline aggregations [do not support subaggregations ](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-aggregations-pipeline.html#search-aggregations-pipeline), there's no subAggregations field in the new struct.
2) Metadata, although supported by Elasticsearch for this aggregation, is not used, since this aggregation doesn't add data to the response. It only reorders parent buckets.
3) No response parser was made for this aggregation since, like said above, this aggregation does not add data to the elasticsearch response, so there's no new data to parse.
=> Bucket sort aggregation

nodes_info.go
This will add the Roles field to node info.
This is exactly the same change made in #745, but in the Elasticsearch 5.X branch.
=> Added roles field to node info

indices_put_alias.go, indices_put_alias_test.go
As described in the Elasticsearch 5.0 and 6.0 documentation, there is an alias action that will remove an index as part of an Index Alias operation. This pull request implements that action.
An example is provided in the documentation just above the section labeled "Filtered Aliases": https://www.elastic.co/guide/en/elasticsearch/reference/6.0/indices-aliases.html#filtered
Relevant Java code: 
Definition of remove index action:
https://github.com/elastic/elasticsearch/blob/8e8fdc4f0efc6ddac866009baa22552668d94a12/server/src/main/java/org/elasticsearch/action/admin/indices/alias/IndicesAliasesRequest.java#L136
Validate function only checks index name on a remove index action:
https://github.com/elastic/elasticsearch/blob/8e8fdc4f0efc6ddac866009baa22552668d94a12/server/src/main/java/org/elas …
=> Add remove index alias action

search.go
As stated in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html
=> nested: Add support for nested queries to search hits

nodes_info.go
when `.Human(true)`, `total_indexing_buffer_in_bytes` is present in the node info api response, e.g.
```
"total_indexing_buffer_in_bytes": "197.9mb",
"total_indexing_buffer": 207591833,
```
`total_indexing_buffer_in_bytes` is string, not int64
Fix #782
=> Fix TotalIndexingBufferInBytes unmarshal error

bulk.go, bulk_test.go
the reason of this change is: all requests are persistent.
if `s.client.PerformRequestWithOptions` (https://github.com/olivere/elastic/blob/release-branch.v6/bulk.go#L249) returns an error, the request won't be reseted, but in some special cases, I would like to decide that.
So by exporting the Reset function, it gives the user the flexibity to reset the queue and possibily write those requests to the file system, if wished.
If this change gets merged, I will make sure to update all other versions.
Great project btw.
=> Change bulk reset func to exportable

retrier.go
This PR allows the use of RetrierFunc as an adapter:
```go
client, err := NewClient(
SetRetrier(RetrierFunc(func(context.Context, int, *http.Request, *http.Response, error) (time.Duration, bool, error){
return 0, false, nil
})),
)
```
Here is an example from the stdlib: https://github.com/golang/go/blob/00ebfcde7f3b6e63447e2a3962975e0a8c3729dd/src/net/http/server.go#L1964-L1973
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/olivere/elastic/827)
=> Allow RetrierFunc to be an adapter

client.go, errors.go
I am using this library against AWS ElasticSearch Service, and found it was constantly logging out that the connection/nodes were dead, whenever the context was cancelled.
I looked and saw you were already handling that, so it took me a while to figure out why it wasn't being caught.
Turns out that the url.Error is wrapping a url.Error that is wrapping the context error, because of transport wrapping a second call to the http client:
https://github.com/olivere/elastic/blob/release-branch.v6/recipes/aws-connect/main.go#L32
I thought about avoiding the second call to the http client, however it is actually a good thing to make that second call after modifying the request, since the http client includes safeguards around not forwarding the authorization headers to untrusted domains.
So a …
=> check for nested context errors

search_queries_simple_query_string.go
fix for #847
Add implementation of QuoteFieldSuffix() to SimpleQueryStringQuery
refers to 
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-simple-query-string-query.html
=> add quote_field_suffix to simple_query_string

indices_open.go
This PR adds the missing parameter to the _open API call, introduced in ES 6.1
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-open-close.html
https://github.com/elastic/elasticsearch/issues/20937
=> Add wait_for_active_shards parameter to the Index Open API

indices_forcemerge.go
The `operation_threading` parameter was removed on Elasticsearch 1.2. Setting it causes an error to be returned.
https://github.com/elastic/elasticsearch/pull/6044
=> Remove operation_threading parameter from Forcemerge

client.go, scroll.go, tasks_list.go
Added ability to append headers to rest calls.
I only added the field on scroll and tasks_list because those were my use case, but this could be useful everywhere.
References issue https://github.com/olivere/elastic/issues/862
=> add headers to request

go.mod
A recent release of go.mod file breaks the backward compatibility of gopkg.in/olivere/elastic.v5 package.
Given
```
$ cat go.mod
require gopkg.in/olivere/elastic.v5 v5.0.53
```
Updating to newer patch version errors out with
```
$ GO111MODULE=on go get -u=patch
go: gopkg.in/olivere/elastic.v5@v5.0.72: go.mod has non-....v5 module path "gopkg.in/olivere/elastic.v5/v5" at revision v5.0.72
go get: error loading module requirements
```
Looking at recent v5 [go.mod file](https://github.com/olivere/elastic/blob/523a0a2a80ee432ac09830b9f9be37e8e2544310/go.mod#L1), why did we change the import path from `gopkg.in/olivere/elastic.v5` to `gopkg.in/olivere/elastic.v5/v5`?
As far as I know, `gopkg.in` packages are handled as a special case in Go modules, see:
https://github.com/golang/go/issues/24099 …
=> Fix Go module path for v5

indices_get_template.go, indices_get_template_test.go
Closes https://github.com/olivere/elastic/issues/868.
Updates the `IndicesGetTemplateResponse` so that the `IndicesGetTemplateResponse` struct defines an `IndexPatterns` member not a `Template` member. In Elasticsearch v6, `index_patterns` is always returned instead of `template`. Adds a test to cover this struct.
As suggested in the issue, checked the response structure in the java source, and the rest of the response seems unchanged.
=> Update GetTemplateResponse for v6.

suggester_context_category.go, suggester_context_category_test.go, suggester_context_geo.go, suggester_context_geo_test.go
1.SuggesterGeoQuery 
1.1. precision -> string array to string (defines precision of the geohash to be indexed, one location pairs one precision)
1.2. value key -> in source map, `value` key not defined in docs
2.SuggesterCategoryQuery
-For category query, we have to use `context` key in source map, and optionally `boost` key 
-For category indexing, I must not use `context` and `boost` keys in source map
=> suggester context query && indexing differences

client.go, client_test.go, response.go, response_test.go, search.go
`elastic` currently decodes the entire ES response uncritically, which can cause out-of-memory errors with very large responses. This adds a `MaxResponseSize()` method to `SearchService` which causes it to error out with `ErrResponseSize` if the ES response exceeds the provided limit.
=> Add SearchService.MaxResponseSize() to guard against OOM situations

search_queries_match.go
i've opened a [issue](https://github.com/olivere/elastic/issues/958)
the weird thing is that even i've dereferenced the pointer cutoffFrequency, these commonTermsQuery and MatchQuery still don't return the same results...
Also check this [blog](https://www.elastic.co/blog/stop-stopping-stop-words-a-look-at-common-terms-query) if you're available and I quote `Note: Common Terms has also been incorporated into the Match query and can be enabled by setting `cutoff_frequency` to a value like 0.001` 
Making me feel that Common Terms Query and Match query can return same results in some way
=> <Fix>: dereferencing the pointer cutoffFrequency, not get the address of cutoffFrequency

example_test.go
`*Client.SetTracer` method is no longer exists.
https://github.com/olivere/elastic/blob/46a8b35d25c08bebb767e8de83d081709af95dc3/example_test.go#L40-L41
So fix example code to use `SetTraceLog` method instead of it.
=> Fix example code to enable trace log

search_queries_exists.go
A simple copy-pasta typo within the godoc
=> godoc: fix typo

highlight.go
Hi! Just noticed a typo in the HighlightQuery API call on in `highlight.go` across several release versions. I suppose folks might already be dependent on the alternate spelling but just in case, I thought I'd submit a PR. Thanks, and once again great library 🙇
=> fix typo in HighlightQuery API call

highlight.go
- Fix the HighlightQuery API call typo on release-branch.v6 based on your fix on master branch.
=> Fix typo in HighlightQuery API call (release-branch.v6)

highlight.go
- Fix the HighlightQuery API call typo on release-branch.v5 based on your fix on master branch.
=> Fix typo in HighlightQuery API call (release-branch.v5)

scroll.go
Upon performing a scrolled search with a scroll size greater than index.max_result_window, Elasticsearch will not process the request and return zero hits, thus leading to a blanket io.EOF error being returned by this client.
As the SearchResult is not returned with the io.EOF error, it is not problematically possible to inspect the root cause of the error, which resulted in us taking a PCAP in order to diagnose the issue.
By returning the SearchResult, along with the error, it allows for inspection of the Shards.Failures list to see the true reason why the query failed.
=> Return the SearchResult, even in the case of EOF error, to allow for root cause analysis

search_queries_terms_set.go
If `values` is not initialized, and no values are provided, this attempts to send a `null` to ES instead of `[]`, resulting in an error.
Matches existing functionality from `TermsQuery` and `IdsQuery`
P.S.  Not sure if this is the right branch, it's just what github chose by default (would actually be nice to get it applied to all releases)
=> Initialize TermsSetQuery values

search_aggs_metrics_top_hits.go
This PR adds a `SearchSource` function to `TopHitsAggregation`, similar to the one exposed by `SearchService`. This makes it easier for users of the library to reuse code between the two cases.
=> Add SearchSource to TopHitsAggregation

search_source.go, search_source_test.go
Currently `NoStoredFields()` has no effect as when the `storedFieldNames` is `nil` as no `stored_fields` property gets sent to Elasticsearch and thus all fields are returned. See https://github.com/olivere/elastic/blob/0534a7b1bf47b1ccf57e905491a641709f8a623d/search_source.go#L406-L413
This PR changes NoStoredFields to set `storedNamesFields` to an empty string slice and thereby send `"stored_fields": []` to Elasticsearch.
=> Fix NoStoredFields to not yield any stored fields

go.mod
This should(tm) be a small update of go.opencensus.io. The reason for the update is a circular-dependency in older versions, leading to https://github.com/golang/lint/issues/436 . The particular version updating to is taken from https://github.com/googleapis/google-cloud-go/issues/1359#issuecomment-480988126.
=> Update go.opencensus.io to 0.20.1

client.go
ES nodes may have their address changed while keeping their ID, in which cases a client may not be able to reconnect to it. This happens for instance with ES nodes deployed as kubernetes pods, after a rolling update.
=> Cannot reconnect if address changes

bulk.go, bulk_test.go
We can already do it for the Search and Scroll services,
and as per https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html
all REST APIs support specifying the filter path.
We would want to do this since if we are bulking a large amount of requests,
all of them needs to be serialized and passed over the network even if
we do not care about the result.
=> Add ability to specify filter path to the Bulk service

README.md, cat_aliases_test.go, cat_allocation_test.go, cat_count_test.go, cat_health_test.go, cat_indices.go, cat_indices_test.go, setup_test.go
This PR changes the tests for the `/_cat/*` endpoints to check that all fields returned by Elasticsearch get JSON-decoded, and fixes a couple of issues found with `CatIndicesResponseRow`.
It also updates the list of implemented cat APIs in the README.
=> Fix decoding of some `CatIndicesResponseRow` fields
